### ISSUE TITLE
uso di mysql nello script Tclima_giorno

### ISSUE THREAD

**Issue by mauromussin** [ARPASMR/meteogiorno#2]
mysql non è installato nel container quindi non può essere usato.
Due soluzioni possibili (mutuamente esclusive):
1. installare mysql nel Dockerfile
2. eseguire una query tramite altro linguaggio (es. python che c'è già oppure R che però andrebbe installato.

**Comment by mariaranci** [comment]
riscritto in python che ha già le librerie per mysql installate
